# Generated by Django 3.0.5 on 2020-11-09 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='confirmations_code',
            field=models.CharField(default=0, max_length=30),
        ),
    ]
