# Generated by Django 3.0.5 on 2020-11-13 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20201109_1257'),
        ('users', '0002_user_confirmations_code'),
    ]

    operations = [
    ]
