# Generated by Django 3.0.5 on 2020-11-14 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20201114_1915'),
        ('users', '0009_user_confirmation_code'),
    ]

    operations = [
    ]
