# Generated by Django 3.0.5 on 2020-11-27 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20201122_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('US', 'User'), ('MD', 'Moderator'), ('AD', 'Administrator')], default='US', max_length=20),
        ),
    ]
