version: '3.3'

volumes:
  postgres_data:
  django_static:

services:
  db:
    image: postgres:12.4
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

  web:
    image: radikkhabibulin/yamdb_final_web
    volumes: 
      - django_static:/code/static/
    restart: always
    ports:
      - "5002:5002"
    depends_on:
      - db
    env_file:
      - ./.env

  nginx:
    image: radikkhabibulin/yamdb_final_nginx
    restart: always
    volumes:
      - django_static:/code/static/
    ports: 
      - "5003:5003"
    depends_on: 
      - web
    env_file:
      - ./.env
