# Generated by Django 3.0.5 on 2020-11-18 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20201115_2322'),
        ('api', '0004_title_rating'),
    ]

    operations = [
    ]
