# Generated by Django 3.0.5 on 2020-11-22 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_merge_20201118_1235'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='titles',
            new_name='title',
        ),
    ]
