# Generated by Django 3.0.5 on 2020-11-23 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20201123_2323'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='created',
            new_name='pub_date',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='created',
            new_name='pub_date',
        ),
    ]
